# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jc-gxQtQwRn_g4hp2efMuRocOSDm1-v2
"""

# app.py
# Streamlit 웹앱: OpenCap .mot/.sto → CSV 변환 + 병합
# pip install streamlit pandas numpy

import io
import re
import zipfile
from datetime import datetime
from typing import Tuple, List, Dict

import numpy as np
import pandas as pd
import streamlit as st


st.set_page_config(page_title="OpenCap MOT → CSV 변환기", page_icon="🚶", layout="wide")

st.title("🚶 OpenCap MOT → CSV 변환기")
st.write("여러 개의 .mot/.sto 파일을 업로드하면 CSV로 변환합니다. ‘병합’ 기능으로 파일명(=ID) 기준 세로 병합도 지원합니다. (OpenSim 설치 불필요)")
st.write("파일을 밑에 배너에 드래그 해주세요!")
st.caption("mimic")
# ---------------------------
# 유틸: .mot/.sto 헤더 파싱 & 본문 읽기
# ---------------------------
def parse_opensim_table(file_bytes: bytes) -> Tuple[pd.DataFrame, Dict[str, str]]:
    """
    OpenSim .mot/.sto 파일을 텍스트로 파싱하여 pandas DataFrame으로 반환.
    헤더 메타정보(키:값)를 dict로 함께 반환.
    규칙:
      - 'endheader' 줄 이후부터 데이터 영역
      - 공백/탭 구분
      - 첫 컬럼(대개 time)을 인덱스 지정하지 않고 그대로 유지
    """
    text = file_bytes.decode("utf-8", errors="ignore")
    lines = text.splitlines()

    header_meta = {}
    header_end_idx = None
    for i, line in enumerate(lines):
        if line.strip().lower() == "endheader":
            header_end_idx = i
            break
        # 키:값 형태 메타 파싱
        if ":" in line:
            k, v = line.split(":", 1)
            header_meta[k.strip()] = v.strip()

    if header_end_idx is None:
        # .mot/.sto 중 일부는 'endheader' 없이 탭/공백 헤더가 바로 나올 수도 있음 → 휴리스틱
        # 첫 데이터 라인 추정: 숫자로 시작하는 첫 줄 인덱스
        header_end_idx = 0
        for i, line in enumerate(lines):
            if re.match(r"^\s*[-+]?(\d+(\.\d+)?([eE][-+]?\d+)?)", line.strip()):
                header_end_idx = i - 1
                break

    # 데이터 영역 텍스트로 재조합
    data_text = "\n".join(lines[header_end_idx + 1 :])

    # 컬럼명 라인 추정: 데이터 첫 줄이 숫자면, 그 윗줄이 컬럼일 가능성이 높음
    # pandas에 바로 던져보고, 전부 숫자이면 헤더 없음으로 간주 후 다시 시도
    try:
        df_try = pd.read_csv(io.StringIO(data_text), delim_whitespace=True)
        # 헤더가 없는 경우(첫 행이 숫자로만 구성) → names 없이 다시 시도
        if all(str(c).replace(".", "", 1).isdigit() for c in df_try.columns[:2]):
            df = pd.read_csv(io.StringIO(data_text), delim_whitespace=True, header=None)
        else:
            df = df_try
    except Exception:
        # 공백이 아닌 탭으로만 구분되어 있을 수도 있음
        df = pd.read_csv(io.StringIO(data_text), sep=r"[\t\s]+", engine="python", header=None)

    # 컬럼명 보정: 헤더 라인이 하나 더 있을 수 있음 (문자+숫자 혼재)
    # 첫 행이 문자열로만 구성돼있으면 컬럼으로 승격
    if df.shape[0] > 1:
        first_row = df.iloc[0].astype(str).tolist()
        if all(re.search(r"[A-Za-z_]", s) for s in first_row):
            df.columns = first_row
            df = df.iloc[1:].reset_index(drop=True)

    # time 컬럼 표준화 (있다면 float로)
    for cand in ["time", "Time", "t", "Time(s)"]:
        if cand in df.columns:
            df.rename(columns={cand: "time"}, inplace=True)
            break

    if "time" in df.columns:
        with np.errstate(all="ignore"):
            df["time"] = pd.to_numeric(df["time"], errors="coerce")

    # 숫자형으로 바꿀 수 있는 컬럼은 가급적 숫자로
    for c in df.columns:
        if c == "time":
            continue
        df[c] = pd.to_numeric(df[c], errors="ignore")

    return df, header_meta


def sanitize_id_from_filename(name: str) -> str:
    base = re.sub(r"\.mot$|\.sto$|\.txt$|\.csv$", "", name, flags=re.IGNORECASE)
    base = re.sub(r"[^\w\-]+", "_", base).strip("_")
    return base or "ID"


# ---------------------------
# 사이드바: 옵션
# ---------------------------
st.sidebar.header("옵션")
merge_on = st.sidebar.checkbox("여러 파일 병합(파일명=ID)", value=True)
id_column_name = st.sidebar.text_input("ID 컬럼명", value="ID")
time_round = st.sidebar.selectbox("time 반올림(옵션)", options=["그대로", "소수점 3자리", "소수점 4자리"], index=0)
zip_prefix = st.sidebar.text_input("다운로드 ZIP/CSV 이름 접두사", value="opencap")

st.sidebar.markdown("---")
st.sidebar.caption("파일명 중복 시 자동으로 `_2`, `_3`를 ID에 부여합니다.")


# ---------------------------
# 본문: 업로드
# ---------------------------
files = st.file_uploader(
    "여러 개의 .mot/.sto 파일을 업로드하세요",
    type=["mot", "sto"],
    accept_multiple_files=True
)

btn_convert = st.button("🔄 변환 실행 (CSV 생성)")
btn_merge   = st.button("📎 병합 CSV 만들기", disabled=(not merge_on))

out_individual: List[Tuple[str, bytes]] = []  # (filename, csv_bytes)
merged_df: pd.DataFrame = pd.DataFrame()


def apply_time_round(df: pd.DataFrame) -> pd.DataFrame:
    if "time" not in df.columns:
        return df
    if time_round == "소수점 3자리":
        df["time"] = df["time"].round(3)
    elif time_round == "소수점 4자리":
        df["time"] = df["time"].round(4)
    return df


# ---------------------------
# 처리 로직
# ---------------------------
if files and (btn_convert or btn_merge):
    id_counts: Dict[str, int] = {}

    merged_rows = []
    with st.spinner("파일 처리 중..."):
        for up in files:
            raw = up.read()
            try:
                df, meta = parse_opensim_table(raw)
            except Exception as e:
                st.error(f"❌ 파싱 실패: {up.name} — {e}")
                continue

            df = apply_time_round(df)

            # 개별 CSV
            csv_bytes = df.to_csv(index=False).encode("utf-8-sig")
            out_individual.append((f"{sanitize_id_from_filename(up.name)}.csv", csv_bytes))

            if merge_on:
                # 파일명 → ID
                _id = sanitize_id_from_filename(up.name)
                # 중복 처리
                if _id in id_counts:
                    id_counts[_id] += 1
                    _id = f"{_id}_{id_counts[_id]}"
                else:
                    id_counts[_id] = 1

                # 병합용: 맨 앞에 ID 컬럼 추가
                df_ = df.copy()
                df_.insert(0, id_column_name, _id)
                merged_rows.append(df_)

    # 다운로드 섹션
    st.subheader("📥 다운로드")

    # (1) 개별 CSV → ZIP
    if out_individual:
        zip_buf = io.BytesIO()
        with zipfile.ZipFile(zip_buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            for fname, b in out_individual:
                zf.writestr(fname, b)
        zip_name = f"{zip_prefix}_csv_{datetime.now().strftime('%Y%m%d_%H%M%S')}.zip"
        st.download_button(
            "개별 CSV (ZIP) 다운로드",
            data=zip_buf.getvalue(),
            file_name=zip_name,
            mime="application/zip"
        )

    # (2) 병합 CSV
    if merge_on and merged_rows:
        merged_df = pd.concat(merged_rows, ignore_index=True)
        # time 컬럼이 있으면 정렬(선택)
        if "time" in merged_df.columns:
            merged_df.sort_values([id_column_name, "time"], inplace=True)
        csv_merged = merged_df.to_csv(index=False).encode("utf-8-sig")
        csv_name = f"{zip_prefix}_merged_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
        st.download_button(
            "병합 CSV 다운로드",
            data=csv_merged,
            file_name=csv_name,
            mime="text/csv"
        )

    # 미리보기
    if out_individual:
        st.markdown("---")
        st.subheader("👀 미리보기")
        # 첫 번째 파일만 살짝 보여주기
        try:
            preview_df, _ = parse_opensim_table(files[0].getvalue())
            st.dataframe(preview_df.head(20), use_container_width=True)
        except Exception:
            pass

elif not files:
    st.info("좌측 또는 위의 영역에서 .mot/.sto 파일을 하나 이상 업로드하세요.")
